# my_locustfiles/Dockerfile
FROM locustio/locust:latest

# Install dependencies
# Add python-dotenv or any other packages your locustfile needs
RUN pip install python-dotenv

# Optionally, if you have a requirements.txt file:
# COPY requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt
