"""adding ifrs9_staging and bog_staging to the loans table

Revision ID: 0c734160ea6d
Revises: 57b43f1b26a4
Create Date: 2025-04-24 00:52:43.857268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c734160ea6d'
down_revision: Union[str, None] = '57b43f1b26a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('ifrs9_stage', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('bog_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'bog_stage')
    op.drop_column('loans', 'ifrs9_stage')
    # ### end Alembic commands ###
