"""initial_schema

Revision ID: 2500e1150d90
Revises: 
Create Date: 2025-12-22 01:29:20.815666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2500e1150d90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clients_group', sa.String(), nullable=True),
    sa.Column('overdue_days_repr_default', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_default_definitions_id'), 'default_definitions', ['id'], unique=False)
    op.create_table('macro_ecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employment_rate', sa.Float(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('gdp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_ecos_id'), 'macro_ecos', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('paystack_plan_code', sa.String(), nullable=False),
    sa.Column('max_loan_data', sa.Integer(), nullable=False),
    sa.Column('max_portfolios', sa.Integer(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_paystack_plan_code'), 'subscription_plans', ['paystack_plan_code'], unique=True)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('accounting_standard', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paystack_customer_code', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_paystack_customer_code'), 'tenants', ['paystack_customer_code'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_email'), 'access_requests', ['email'], unique=False)
    op.create_index(op.f('ix_access_requests_id'), 'access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_access_requests_tenant_id'), 'access_requests', ['tenant_id'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('paystack_subscription_code', sa.String(), nullable=False),
    sa.Column('paystack_customer_code', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_id'), 'tenant_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_paystack_customer_code'), 'tenant_subscriptions', ['paystack_customer_code'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_paystack_subscription_code'), 'tenant_subscriptions', ['paystack_subscription_code'], unique=True)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('recovery_email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('job_role', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.create_table('help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_id'), 'help', ['id'], unique=False)
    op.create_index(op.f('ix_help_tenant_id'), 'help', ['tenant_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('customer_type', sa.String(), nullable=True),
    sa.Column('funding_source', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('repayment_source', sa.Boolean(), nullable=True),
    sa.Column('credit_risk_reserve', sa.String(), nullable=True),
    sa.Column('loan_assets', sa.String(), nullable=True),
    sa.Column('ecl_impairment_account', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('loan_count', sa.Integer(), nullable=False),
    sa.Column('ecl_staging_config', sa.JSON(), nullable=True),
    sa.Column('bog_staging_config', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('subscription_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('current_loan_count', sa.Integer(), nullable=False),
    sa.Column('current_portfolio_count', sa.Integer(), nullable=False),
    sa.Column('current_team_count', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_usage_id'), 'subscription_usage', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_usage_subscription_id'), 'subscription_usage', ['subscription_id'], unique=True)
    op.create_table('calculation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('calculation_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('total_provision', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('provision_percentage', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_results_id'), 'calculation_results', ['id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('other_names', sa.String(), nullable=True),
    sa.Column('residential_address', sa.String(), nullable=True),
    sa.Column('postal_address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('previous_employee_no', sa.String(), nullable=True),
    sa.Column('social_security_no', sa.String(), nullable=True),
    sa.Column('voters_id_no', sa.String(), nullable=True),
    sa.Column('employment_date', sa.Date(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('next_of_kin_contact', sa.String(), nullable=True),
    sa.Column('next_of_kin_address', sa.String(), nullable=True),
    sa.Column('search_name', sa.String(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_last_name'), 'clients', ['last_name'], unique=False)
    op.create_index(op.f('ix_clients_search_name'), 'clients', ['search_name'], unique=False)
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('feedback_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feedback_id')
    )
    op.create_table('guarantees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('guarantor', sa.String(), nullable=False),
    sa.Column('pledged_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guarantees_id'), 'guarantees', ['id'], unique=False)
    op.create_index(op.f('ix_guarantees_tenant_id'), 'guarantees', ['tenant_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('loan_no', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('loan_issue_date', sa.Date(), nullable=True),
    sa.Column('deduction_start_period', sa.Date(), nullable=True),
    sa.Column('submission_period', sa.Date(), nullable=True),
    sa.Column('maturity_period', sa.Date(), nullable=True),
    sa.Column('location_code', sa.String(), nullable=True),
    sa.Column('dalex_paddy', sa.String(), nullable=True),
    sa.Column('team_leader', sa.String(), nullable=True),
    sa.Column('loan_type', sa.String(), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loan_term', sa.Integer(), nullable=True),
    sa.Column('administrative_fees', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_interest', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_collectible', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_loan_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('monthly_installment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('principal_paid2', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_paid2', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_paid2', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('outstanding_loan_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('accumulated_arrears', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ndia', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('prevailing_posted_repayment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('prevailing_due_payment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_missed_deduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('admin_charge', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('deduction_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ifrs9_stage', sa.String(), nullable=True),
    sa.Column('bog_stage', sa.String(), nullable=True),
    sa.Column('bog_prov_rate', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amortised_bal', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('adjusted_amortised_bal', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('theoretical_balance', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('ead', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('lgd', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('pd', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('eir', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('ecl_12', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('ecl_lifetime', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('final_ecl', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('bog_provision', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('calculation_date', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['tenant_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_no'), 'loans', ['loan_no'], unique=False)
    op.create_index(op.f('ix_loans_tenant_id'), 'loans', ['tenant_id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_records', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_id'), 'quality_issues', ['id'], unique=False)
    op.create_index(op.f('ix_quality_issues_tenant_id'), 'quality_issues', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_name', sa.String(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('staging_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('staging_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staging_results_id'), 'staging_results', ['id'], unique=False)
    op.create_table('other_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('extending_party', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_other_loans_id'), 'other_loans', ['id'], unique=False)
    op.create_table('quality_issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_issue_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quality_issue_id'], ['quality_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issue_comments_id'), 'quality_issue_comments', ['id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('collateral_description', sa.Text(), nullable=True),
    sa.Column('collateral_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('forced_sale_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('method_of_valuation', sa.String(), nullable=True),
    sa.Column('cash_or_non_cash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_id'), 'securities', ['id'], unique=False)
    op.create_index(op.f('ix_securities_tenant_id'), 'securities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_tenant_id'), table_name='securities')
    op.drop_index(op.f('ix_securities_id'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_quality_issue_comments_id'), table_name='quality_issue_comments')
    op.drop_table('quality_issue_comments')
    op.drop_index(op.f('ix_other_loans_id'), table_name='other_loans')
    op.drop_table('other_loans')
    op.drop_index(op.f('ix_staging_results_id'), table_name='staging_results')
    op.drop_table('staging_results')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_quality_issues_tenant_id'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_loans_tenant_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_loan_no'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_guarantees_tenant_id'), table_name='guarantees')
    op.drop_index(op.f('ix_guarantees_id'), table_name='guarantees')
    op.drop_table('guarantees')
    op.drop_table('feedback_likes')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_search_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_last_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_calculation_results_id'), table_name='calculation_results')
    op.drop_table('calculation_results')
    op.drop_index(op.f('ix_subscription_usage_subscription_id'), table_name='subscription_usage')
    op.drop_index(op.f('ix_subscription_usage_id'), table_name='subscription_usage')
    op.drop_table('subscription_usage')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_help_tenant_id'), table_name='help')
    op.drop_index(op.f('ix_help_id'), table_name='help')
    op.drop_table('help')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_paystack_subscription_code'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_paystack_customer_code'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_access_requests_tenant_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_email'), table_name='access_requests')
    op.drop_table('access_requests')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_paystack_customer_code'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_subscription_plans_paystack_plan_code'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_macro_ecos_id'), table_name='macro_ecos')
    op.drop_table('macro_ecos')
    op.drop_index(op.f('ix_default_definitions_id'), table_name='default_definitions')
    op.drop_table('default_definitions')
    # ### end Alembic commands ###
