"""remove unique constraint for loan to allow duplicates

Revision ID: 5fc1007d7212
Revises: aa3f19d6ee22
Create Date: 2025-04-04 22:40:55.477344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc1007d7212'
down_revision: Union[str, None] = 'aa3f19d6ee22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_portfolio_loan_no', 'loans', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_portfolio_loan_no', 'loans', ['portfolio_id', 'loan_no'])
    # ### end Alembic commands ###
