"""adding ecl and bog staging config columns in portfolio table

Revision ID: 83fc77dc7fb7
Revises: e489ae95a7df
Create Date: 2025-05-02 07:59:39.912365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fc77dc7fb7'
down_revision: Union[str, None] = 'e489ae95a7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('ecl_staging_config', sa.JSON(), nullable=True))
    op.add_column('portfolios', sa.Column('bog_staging_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'bog_staging_config')
    op.drop_column('portfolios', 'ecl_staging_config')
    # ### end Alembic commands ###
