"""remove unique parameter from loan_no

Revision ID: aa3f19d6ee22
Revises: dfa646637596
Create Date: 2025-04-04 20:39:27.487357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3f19d6ee22'
down_revision: Union[str, None] = 'dfa646637596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loans_loan_no', table_name='loans')
    op.create_index(op.f('ix_loans_loan_no'), 'loans', ['loan_no'], unique=False)
    op.create_unique_constraint('uix_portfolio_loan_no', 'loans', ['portfolio_id', 'loan_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_portfolio_loan_no', 'loans', type_='unique')
    op.drop_index(op.f('ix_loans_loan_no'), table_name='loans')
    op.create_index('ix_loans_loan_no', 'loans', ['loan_no'], unique=True)
    # ### end Alembic commands ###
