"""updating field capacity to 30

Revision ID: c61c9288def2
Revises: 54ce69143111
Create Date: 2025-04-24 15:10:58.623949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61c9288def2'
down_revision: Union[str, None] = '54ce69143111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'bog_prov_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'amortised_bal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'adjusted_amortised_bal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'theoretical_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ead',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'lgd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'pd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'eir',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_12',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_lifetime',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'final_ecl',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'bog_provision',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=32, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'bog_provision',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'final_ecl',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_lifetime',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_12',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'eir',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'ecl',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'pd',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'lgd',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'ead',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'theoretical_balance',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'adjusted_amortised_bal',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'amortised_bal',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('loans', 'bog_prov_rate',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
