"""rename credit_source column to credit_risk_reserve

Revision ID: dba0fa6bc5b8
Revises: 710a9dd9e61f
Create Date: 2025-03-23 14:35:06.467477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba0fa6bc5b8'
down_revision: Union[str, None] = '710a9dd9e61f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('credit_risk_reserve', sa.String(), nullable=True))
    op.drop_column('portfolios', 'credit_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('credit_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('portfolios', 'credit_risk_reserve')
    # ### end Alembic commands ###
