"""updating db

Revision ID: e486a89395d3
Revises: c61c9288def2
Create Date: 2025-04-29 13:45:03.456838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e486a89395d3'
down_revision: Union[str, None] = 'c61c9288def2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('calculation_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('loans', 'bog_prov_rate',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'amortised_bal',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'adjusted_amortised_bal',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'theoretical_balance',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ead',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'lgd',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'pd',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'eir',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_12',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_lifetime',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'final_ecl',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'bog_provision',
               existing_type=sa.NUMERIC(precision=32, scale=2),
               type_=sa.Numeric(precision=38, scale=2),
               existing_nullable=True)
    op.drop_column('loans', 'ecl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('ecl', sa.NUMERIC(precision=32, scale=2), autoincrement=False, nullable=True))
    op.alter_column('loans', 'bog_provision',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'final_ecl',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_lifetime',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ecl_12',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'eir',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'pd',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'lgd',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'ead',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'theoretical_balance',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'adjusted_amortised_bal',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'amortised_bal',
               existing_type=sa.Numeric(precision=38, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.alter_column('loans', 'bog_prov_rate',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=32, scale=2),
               existing_nullable=True)
    op.drop_column('loans', 'calculation_date')
    # ### end Alembic commands ###
