"""Link portfolios and clients

Revision ID: efab7a69c86b
Revises: fa8e326cb122
Create Date: 2025-03-15 18:15:57.852184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efab7a69c86b"
down_revision: Union[str, None] = "fa8e326cb122"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("portfolio_id", sa.Integer(), nullable=False))
    op.add_column("clients", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("clients", sa.Column("other_names", sa.String(), nullable=False))
    op.drop_index("ix_clients_lastname", table_name="clients")
    op.create_index(
        op.f("ix_clients_last_name"), "clients", ["last_name"], unique=False
    )
    op.create_foreign_key(None, "clients", "portfolios", ["portfolio_id"], ["id"])
    op.drop_column("clients", "othernames")
    op.drop_column("clients", "lastname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column("lastname", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "clients",
        sa.Column("othernames", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_index(op.f("ix_clients_last_name"), table_name="clients")
    op.create_index("ix_clients_lastname", "clients", ["lastname"], unique=False)
    op.drop_column("clients", "other_names")
    op.drop_column("clients", "last_name")
    op.drop_column("clients", "portfolio_id")
    # ### end Alembic commands ###
