"""Link portfolios and loans

Revision ID: fa8e326cb122
Revises: 773b1bf97ef0
Create Date: 2025-03-15 16:28:38.854618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa8e326cb122"
down_revision: Union[str, None] = "773b1bf97ef0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loans", sa.Column("portfolio_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "loans", "portfolios", ["portfolio_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "loans", type_="foreignkey")
    op.drop_column("loans", "portfolio_id")
    # ### end Alembic commands ###
