"""make some loan and client fields nullable

Revision ID: faba428b1ef5
Revises: 5fc1007d7212
Create Date: 2025-04-07 02:34:05.433573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faba428b1ef5'
down_revision: Union[str, None] = '5fc1007d7212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'other_names',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'loan_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'loan_issue_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('loans', 'loan_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('loans', 'loan_term',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'loan_term',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('loans', 'loan_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('loans', 'loan_issue_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('loans', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('loans', 'loan_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'other_names',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
