"""add balance_difference to loans

Revision ID: fc7dfb5a56c7
Revises: 2500e1150d90
Create Date: 2026-02-20 13:27:16.968676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7dfb5a56c7'
down_revision: Union[str, None] = '2500e1150d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('balance_difference', sa.Numeric(precision=38, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'balance_difference')
    # ### end Alembic commands ###
