"""adding credit loss fields

Revision ID: fe172cb8af3c
Revises: 0c734160ea6d
Create Date: 2025-04-24 03:06:10.476616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe172cb8af3c'
down_revision: Union[str, None] = '0c734160ea6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('bog_prov_rate', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('amortised_bal', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('adjusted_amortised_bal', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('theoretical_balance', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('ead', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('lgd', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('pd', sa.Float(), nullable=True))
    # op.add_column('loans', sa.Column('ecl', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('eir', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('pv_ecl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'pv_ecl')
    op.drop_column('loans', 'eir')
    op.drop_column('loans', 'ecl')
    op.drop_column('loans', 'pd')
    op.drop_column('loans', 'lgd')
    op.drop_column('loans', 'ead')
    op.drop_column('loans', 'theoretical_balance')
    op.drop_column('loans', 'adjusted_amortised_bal')
    op.drop_column('loans', 'amortised_bal')
    op.drop_column('loans', 'bog_prov_rate')
    # ### end Alembic commands ###
