"""create subscription_plans table

Revision ID: 476264579e83
Revises: d263405e3d21
Create Date: 2025-12-17 00:08:03.088375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476264579e83'
down_revision: Union[str, None] = 'd263405e3d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('paystack_plan_code', sa.String(), nullable=False),
    sa.Column('max_loan_data', sa.Integer(), nullable=False),
    sa.Column('max_portfolios', sa.Integer(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_paystack_plan_code'), 'subscription_plans', ['paystack_plan_code'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('paystack_subscription_code', sa.String(), nullable=False),
    sa.Column('paystack_customer_code', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_paystack_customer_code'), 'user_subscriptions', ['paystack_customer_code'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_paystack_subscription_code'), 'user_subscriptions', ['paystack_subscription_code'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('subscription_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('current_loan_count', sa.Integer(), nullable=False),
    sa.Column('current_portfolio_count', sa.Integer(), nullable=False),
    sa.Column('current_team_count', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_usage_id'), 'subscription_usage', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_usage_subscription_id'), 'subscription_usage', ['subscription_id'], unique=True)
    op.add_column('loans', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loans', 'user_subscriptions', ['subscription_id'], ['id'])
    op.add_column('portfolios', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('portfolios', sa.Column('loan_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'portfolios', 'user_subscriptions', ['subscription_id'], ['id'])
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_paystack_customer_code'), 'users', ['paystack_customer_code'], unique=False)
    op.create_foreign_key(None, 'users', 'user_subscriptions', ['current_subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_paystack_customer_code'), table_name='users')
    op.alter_column('users', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_column('portfolios', 'loan_count')
    op.drop_column('portfolios', 'subscription_id')
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.drop_column('loans', 'subscription_id')
    op.drop_index(op.f('ix_subscription_usage_subscription_id'), table_name='subscription_usage')
    op.drop_index(op.f('ix_subscription_usage_id'), table_name='subscription_usage')
    op.drop_table('subscription_usage')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_paystack_subscription_code'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_paystack_customer_code'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_subscription_plans_paystack_plan_code'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
