"""adding final_ecl and bog_provision fields to loans table

Revision ID: 54ce69143111
Revises: fe172cb8af3c
Create Date: 2025-04-24 06:12:25.518689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ce69143111'
down_revision: Union[str, None] = 'fe172cb8af3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('ecl_12', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('ecl_lifetime', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('final_ecl', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('bog_provision', sa.Float(), nullable=True))
    op.drop_column('loans', 'pv_ecl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('pv_ecl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('loans', 'bog_provision')
    op.drop_column('loans', 'final_ecl')
    op.drop_column('loans', 'ecl_lifetime')
    op.drop_column('loans', 'ecl_12')
    # ### end Alembic commands ###
