"""adding file_path and status columns to reports table

Revision ID: 8b37e2c9ec34
Revises: 83fc77dc7fb7
Create Date: 2025-05-06 01:32:29.124845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b37e2c9ec34'
down_revision: Union[str, None] = '83fc77dc7fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'file_path')
    # ### end Alembic commands ###
