"""amending tables for fast deletion

Revision ID: d59ab5d0a61a
Revises: 8b37e2c9ec34
Create Date: 2025-07-10 21:47:33.474108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59ab5d0a61a'
down_revision: Union[str, None] = '8b37e2c9ec34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET statement_timeout = '5min'")
    op.drop_constraint('clients_portfolio_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('guarantees_portfolio_id_fkey', 'guarantees', type_='foreignkey')
    op.create_foreign_key(None, 'guarantees', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('loans_portfolio_id_fkey', 'loans', type_='foreignkey')
    op.create_foreign_key(None, 'loans', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loans', type_='foreignkey')
    op.create_foreign_key('loans_portfolio_id_fkey', 'loans', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_constraint(None, 'guarantees', type_='foreignkey')
    op.create_foreign_key('guarantees_portfolio_id_fkey', 'guarantees', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_portfolio_id_fkey', 'clients', 'portfolios', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###
