"""Add tenant registration fields

Revision ID: e5486b54d993
Revises: 527520fb0e43
Create Date: 2025-12-21 10:48:49.334951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5486b54d993'
down_revision: Union[str, None] = '527520fb0e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('country', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('accounting_standard', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_role')
    op.drop_column('users', 'phone_number')
    op.drop_column('tenants', 'accounting_standard')
    op.drop_column('tenants', 'country')
    op.drop_column('tenants', 'industry')
    # ### end Alembic commands ###
